### ISSUE TITLE
error compile w7

### ISSUE THREAD

**Issue by tcpipchip** [nrf-rs/nrf-hal#251]
Hi

is that a windows 7 problem only ?

![image](https://user-images.githubusercontent.com/11488460/96479107-df4ade80-120e-11eb-8362-5cf89fdbcb0e.png)

Can you help me  ?

**Comment by jonas-schievink** [comment]
`cargo-embed` is a host application, so it cannot be built for microcontroller targets like `thumbv7em-none-eabihf`. It also isn't part of the nRF HALs, but probe-rs (https://github.com/probe-rs/cargo-embed).

This looks like a misconfiguration of your system, since it is trying to compile cargo-embed for `thumbv7em-none-eabihf`.

**Comment by tcpipchip** [comment]
@jonas-schievink 
Thanks to answer fast
The true is that i want to compile this
https://github.com/nrf-rs/nrf-hal/tree/master/examples/blinky-button-demo 
to the NRF52832/NRF52840
Can you instruct me ?

**Comment by tcpipchip** [comment]
this ?
![image](https://user-images.githubusercontent.com/11488460/96485075-e1af3780-1212-11eb-8a12-ddf800675887.png)

**Comment by tcpipchip** [comment]
success compile!

Help me about the error that i got after try to install probe-run
![image](https://user-images.githubusercontent.com/11488460/96487273-69954180-1213-11eb-9094-9ae6eb2289b8.png)

**Comment by jonas-schievink** [comment]
I don't know, but it's not an nrf-hal problem, so closing this issue. With general Rust questions like this, I recommend asking on https://users.rust-lang.org/.
